# Environment Configuration Steps

# mamba create -n biomed-fm python=3.11 -y
# conda activate nasa

# mamba install pytorch torchvision torchaudio pytorch-cuda=12.1 -c pytorch -c nvidia -y

# mamba env update --file environment.yml --prune

# For archs4 preprocessing, archs4py is only available on pip so make a separate environment
# mamba create -n archs4 python=3.11
# conda activate archs4
# pip install archs4py

name: nasa
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - numpy
  - pandas
  - pyarrow
  - matplotlib
  - scikit-learn
  - tqdm
  - wandb
  - h5py


