#!/usr/bin/env python3
"""Download a chunk of expression data from the mouse ARCHS4 H5 file.

Usage:
  python3 split_mouse_data.py --chunk_id 0 --chunk_size 5000

Requires passing_indices.npy generated by scan_mouse_h5.py.
"""

import argparse
import os
import sys
import time

import archs4py as a4
import h5py
import numpy as np
import pandas as pd

parser = argparse.ArgumentParser(description="Download a chunk from mouse ARCHS4 H5")
parser.add_argument("--datapath", type=str,
                    default="/media/volume/bulkrnamouse/mouse_gene_v2.latest.h5",
                    help="H5 file path")
parser.add_argument("--outputdir", type=str,
                    default="/media/volume/bulkrnamouse/mousedata/",
                    help="Output directory")
parser.add_argument("--chunk_id", type=int, required=True,
                    help="Chunk index to download")
parser.add_argument("--chunk_size", type=int, default=5000,
                    help="Number of samples per chunk")
args = parser.parse_args()

os.makedirs(args.outputdir, exist_ok=True)

# Load pre-filtered indices
indices_file = os.path.join(args.outputdir, 'passing_indices.npy')
if not os.path.exists(indices_file):
    print(f"Error: no pre-filtered indices at {indices_file}. Run scan_mouse_h5.py first.")
    sys.exit(1)

all_indices = np.load(indices_file)
n_total = len(all_indices)

i = args.chunk_id
start = i * args.chunk_size
end = min((i + 1) * args.chunk_size, n_total)

if start >= n_total:
    print(f"Chunk {i} exceeds {n_total} samples. Nothing to do.")
    sys.exit(0)

shard = all_indices[start:end].tolist()
num_chunks = (n_total + args.chunk_size - 1) // args.chunk_size
print(f"Chunk {i}/{num_chunks - 1}: {len(shard)} samples (pool of {n_total})")

# Download expression
t0 = time.time()
df = a4.data.index(args.datapath, shard)
print(f"Downloaded {df.shape} in {(time.time() - t0) / 60:.2f} minutes")

# Format
df = df.reset_index()
df = df.rename(columns={df.columns[0]: 'genes'})

# Save
out_file = os.path.join(args.outputdir, f'input_chunk_{i:03d}.parquet')
df.to_parquet(out_file, engine='pyarrow', compression='snappy')
print(f"Saved {out_file} in {(time.time() - t0) / 60:.2f} minutes")
